 var people = [
    {
        logo:'./static/img/puxun.png',
        name:'蒲逊',
        company:'红杉资本',
        position:'副总裁'
       
    },
    {
        logo:'./static/img/maxuemei.png',
        name:'马学美',
        company:'深创投',
        position:'投资总监'
    },
    {
        logo:'./static/img/tanweihao.png',
        name:'谭伟豪',
        company:'深港基金',
        position:'创始合伙人'
    },
    {
        logo:'./static/img/songpingping.png',
        name:'宋萍萍',
        company:'东方富海',
        position:'合伙人'
    },
    {
        logo:'./static/img/lihao.png',
        name:'李昊',
        company:'君盛投资',
        position:'合伙人'
    },
    {
        logo:'./static/img/zhouqi.png',
        name:'周奇',
        company:'金沙江',
        position:'合伙人'
    },
    {
        logo:'./static/img/baiyunfan.png',
        name:'白云帆',
        company:'松禾资本',
        position:'董事总经理'
    },
    {
        logo:'./static/img/liangying.png',
        name:'梁颖',
        company:'联想创投',
        position:'董事总经理'
    },
    {
        logo:'./static/img/renjunzhao.png',
        name:'任俊照',
        company:'达晨创投',
        position:'合伙人'
    },
    {
        logo:'./static/img/zenglingxi.png',
        name:'曾令西',
        company:'力合科创集团',
        position:'力合生物 总经理'
    },
    {
        logo:'./static/img/zhangyang.png',
        name:'张扬',
        company:'清源投资',
        position:'副总经理'
    },
    {
        logo:'./static/img/jiajunxin.png',
        name:'贾君新',
        company:'新恒利达',
        position:'董事长'
    },
    {
        logo:'./static/img/suijianfeng.png',
        name:'隋建峰',
        company:'启迪之星(深圳) ',
        position:'总经理'
    },
    {
        logo:'./static/img/ouyang.png',
        name:'欧阳光耀',
        company:'澳银资本',
        position:'合伙人'
    },
    {
        logo:'./static/img/liubingyun.png',
        name:'刘冰云',
        company:'赛马资本',
        position:'董事长'
    },
    {
        logo:'./static/img/dailu.png',
        name:'戴露',
        company:'红秀资本',
        position:'董事长'
    },
    {
        logo:'./static/img/yeyongsheng.png',
        name:'叶永圣',
        company:'东方盛鼎',
        position:'总经理'
    }
    
]

export  default  people;